# Dataframe

### Connecting to Oracle Database

In [1]:
import oracledb 

username = "system"  
password = "password"  
host = "localhost" 
port = 1521  
service_name = "free" 
connection_string = f"{username}/{password}@{host}:{port}/{service_name}"
connection = oracledb.connect(connection_string)
print("Connection established.")

Connection established.

Python-oracledb can query directly to a data frame format, and can also insert data frames into Oracle Database. This can improve performance and reduce memory requirements when your application uses Python data frame libraries such as Apache PyArrow, Pandas, Polars, NumPy, Dask, PyTorch, or writes files in Apache Parquet format.

Python-oracledb has two methods for querying into a DataFrame:
- `Connection.fetch_df_all()` fetches all rows from a query
- `Connection.fetch_df_batches()` implements an iterator for fetching batches of rows

Installing PyArrow library via pip in-line command execution

In [5]:
! pip install pyarrow

Requirement already satisfied: pyarrow in /Users/v0idgy/miniconda3/lib/python3.13/site-packages (24.0.0)

In [6]:
! pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (79 kB)
Requirement already satisfied: numpy>=1.26.0 in /Users/v0idgy/miniconda3/lib/python3.13/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/v0idgy/miniconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/v0idgy/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp313-cp313-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 1.0 MB/s  0:00:090m eta 0:00:01
Installing collected packages: pandas
Successfully installed pandas-3.0.3

Basic Dataframe Creation with Pyarrow and Pandas

In [33]:
import pyarrow

sql = "select * from fdp_participants"
odf = connection.fetch_df_all(statement=sql)

# Get a Pandas DataFrame from the data
df = pyarrow.table(odf).to_pandas()

In [34]:
df

    ID         NAME  IS_ACTIVE         JOINED_DATE
0  1.0    Dr. Smith       True 2026-05-12 03:52:08
1  2.0  Prof. Jones      False 2026-05-02 03:52:08

In [35]:
df.head()

    ID         NAME  IS_ACTIVE         JOINED_DATE
0  1.0    Dr. Smith       True 2026-05-12 03:52:08
1  2.0  Prof. Jones      False 2026-05-02 03:52:08

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           2 non-null      float64
 1   NAME         2 non-null      str
 2   IS_ACTIVE    2 non-null      bool
 3   JOINED_DATE  2 non-null      datetime64[s]
dtypes: bool(1), datetime64[s](1), float64(1), str(1)
memory usage: 202.0 bytes

In [37]:
df.describe()

             ID          JOINED_DATE
count  2.000000                    2
mean   1.500000  2026-05-07 03:52:08
min    1.000000  2026-05-02 03:52:08
25%    1.250000  2026-05-04 15:52:08
50%    1.500000  2026-05-07 03:52:08
75%    1.750000  2026-05-09 15:52:08
max    2.000000  2026-05-12 03:52:08
std    0.707107                  NaN